// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skuxzowvzrznsimiyxrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrdXh6b3d2enJ6bnNpbWl5eHJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMzIzOTgsImV4cCI6MjA3MDkwODM5OH0.v8szFKwAXuxSy67xGnVFjtPfQt1Fcei0E47_2c6PQ4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});